-- 코드를 입력하세요
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES*PRICE) AS TOTAL_SALES
FROM (
        SELECT BOOK_ID, SUM(SALES) AS SALES
        FROM BOOK_SALES
        WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
        GROUP BY BOOK_ID
    ) BS
    LEFT JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
    LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC
