-- 코드를 입력하세요
WITH U_21 AS (
    SELECT USER_ID 
    FROM USER_INFO 
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR(SALES_DATE) AS YEAR
        , MONTH(SALES_DATE) AS MONTH
        , COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
        , ROUND(
            COUNT(DISTINCT USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM U_21), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID FROM U_21) 
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH
            