-- 코드를 입력하세요
WITH USER21 AS(
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
)

SELECT YEAR(SALES_DATE) AS YEAR
    , MONTH(SALES_DATE) AS MONTH
    , COUNT(DISTINCT USER_ID) AS PUCHASED_USERS
    , ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM USER21), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID FROM USER21)
GROUP BY YEAR, MONTH 
ORDER BY YEAR, MONTH 