-- 코드를 입력하세요
SELECT O.PRODUCT_ID, PRODUCT_NAME, PRICE*SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P
    LEFT JOIN FOOD_ORDER O ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE MONTH(PRODUCE_DATE) = 5
GROUP BY O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID ASC