WITH HIST AS (
    SELECT HISTORY_ID, H.CAR_ID, CAR_TYPE, DAILY_FEE, START_DATE, END_DATE
        , DATEDIFF(END_DATE, START_DATE)+1 AS DURATION
        , CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 BETWEEN 7 AND 29 THEN '7일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE)+1 BETWEEN 30 AND 89 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상'
            ELSE '해당 없음'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
    WHERE CAR_TYPE = '트럭'
), DISC AS (
    SELECT PLAN_ID, CAR_TYPE, DURATION_TYPE
        , ROUND((DISCOUNT_RATE/100), 2) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭'
)

SELECT H.HISTORY_ID
    , CASE WHEN DISCOUNT_RATE IS NULL THEN ROUND(H.DURATION*DAILY_FEE, 0)
            ELSE ROUND((H.DURATION*DAILY_FEE)*(1-DISCOUNT_RATE),0)
    END AS FEE
FROM HIST H
    LEFT JOIN DISC D ON H.DURATION_TYPE = D.DURATION_TYPE
ORDER BY FEE DESC, H.HISTORY_ID DESC

# SELECT *
# FROM HIST H
#     LEFT JOIN DISC D ON H.DURATION_TYPE = D.DURATION_TYPE

    
    



