-- 코드를 입력하세요
WITH TYPES AS (
    SELECT HISTORY_ID, H.CAR_ID, CAR_TYPE, DAILY_FEE
        , DATEDIFF(END_DATE, START_DATE)+1 AS DURATIONS
        , CASE WHEN (DATEDIFF(END_DATE, START_DATE)+1) >= 90 THEN '90일 이상'
            WHEN (DATEDIFF(END_DATE, START_DATE)+1) >= 30 THEN '30일 이상'
            WHEN (DATEDIFF(END_DATE, START_DATE)+1) >= 7 THEN '7일 이상'
            ELSE NULL 
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = H.CAR_ID
    WHERE CAR_TYPE = '트럭'
), TD AS (
    SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE/100 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
)

SELECT HISTORY_ID
    , CASE WHEN P.DURATION_TYPE IS NULL THEN ROUND(DAILY_FEE*DURATIONS, 0)
        ELSE ROUND(DAILY_FEE*DURATIONS*(1-DISCOUNT_RATE),0)  
    END AS FEE
FROM TYPES P
    LEFT JOIN TD D ON D.DURATION_TYPE = P.DURATION_TYPE
HAVING FEE IS NOT NULL
ORDER BY FEE DESC, HISTORY_ID DESC

