-- 코드를 입력하세요
WITH TT1 AS (  
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
), TT2 AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT T1.FLAVOR
FROM TT1 T1
    JOIN TT2 T2 ON T1.FLAVOR = T2.FLAVOR
ORDER BY T1.TOTAL_ORDER + T2.TOTAL_ORDER DESC
LIMIT 3
