WITH PCD AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
), CCD AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
), OCD AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT CASE 
        WHEN SKILL_CODE & (SELECT CODE FROM PCD) 
            AND SKILL_CODE & (SELECT CODE FROM OCD) THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM CCD) THEN 'B'
        WHEN SKILL_CODE & (SELECT CODE FROM OCD) THEN 'C'
    END AS GRADE, ID, EMAIL
FROM DEVELOPERS
HAVING GRADE IS NOT NULL
ORDER BY GRADE, ID
